name: Release Ockam Examples

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      ockam_release_tag:
        description: Ockam release tag
        required: true
      branch_name:
        description: Branch name to create pull request
        required: true

jobs:
  release_examples:
    name: Release - examples
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Docs Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
          path: docs

      - name: Checkout Ockam Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          path: examples
          ref: ${{ github.event.inputs.ockam_release_tag }}

      - name: Update Examples
        run: |
          git checkout -B ${{ github.event.inputs.branch_name }}
          DOCS_HOME="documentation" OCKAM_HOME="examples" ./examples/tools/docs/update_md.sh

      - name: Push Changes
        run: |
          # Check if there are updated files
          
